#
# Makefile for modem (radio) control drivers
#

obj-$(CONFIG_RADIO_CTRL_CLASS)   += radio_class.o
obj-$(CONFIG_MDM6600_CTRL_AGENT) += mdm6600_ctrl_agent.o
obj-$(CONFIG_WRIGLEY_CTRL)       += wrigley_ctrl.o
